force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <label>Nom de Interview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>The duration of the interview</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/InterviewEndDate__c.field-meta.xml
<CustomField>
    <fullName>InterviewEndDate__c</fullName>
    <label>InterviewEndDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/InterviewStartDate__c.field-meta.xml
<CustomField>
    <fullName>InterviewStartDate__c</fullName>
    <label>InterviewStartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SRV_InterviewService.cls
public with sharing class SRV_InterviewService {

    public static void calculateInterviewEndDate(List<Interview__c> interviews) {
        if(interviews==null || interviews.size()==0)
            return;

        for( Interview__c interview: interviews) {
            interview.InterviewEndDate__c = interview.InterviewStartDate__c.addHours(Integer.valueOf(interview.Duration__c));
        }
    }
}