force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <label>Nom de Interview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>The duration of the interview</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/InterviewStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>InterviewStartDateTime__c</fullName>
    <label>InterviewStartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MyTestDataFactory.cls
public class MyTestDataFactory {
    public static List<Candidate__c> createCandidateRecords(String Name, Integer Count, Boolean doInsert) {
        List<Candidate__c> candidateList = new List<Candidate__c>();

        for (Integer i = 0; i < Count; i++) {
            Candidate__c candidate = new Candidate__c();
            candidate.First_Name__c = Name;
            candidate.Last_Name__c = i.format();
            System.debug(candidate.First_Name__c + ' '+ candidate.Last_Name__c);
            candidateList.add(candidate);
        }

        if(doInsert) {
            insert candidateList;
        }

        return candidateList;
    }

    public static List<Interview__c> createInterviewRecords(String Name, DateTime interviewDate, List<Candidate__c> candidateList, Boolean doInsert) {
        List<Interview__c> interviewList = new List<Interview__c>();

        for (Integer i = 0; i < candidateList.size(); i++) {
            Interview__c interview = new Interview__c();
            interview.Candidate__c = candidateList[i].Id;
            interview.Name =  Name + i;
            interview.Duration__c = 2;
            interview.InterviewStartDateTime__c = interviewDate.addDays(i);
            System.debug(interview.Name);
            interviewList.add(interview);
        }

        if(doInsert) {
            insert interviewList;
        }

        return interviewList;
    }

}