force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <label>Nom de Interview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>The duration of the interview</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/InterviewStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>InterviewStartDateTime__c</fullName>
    <label>InterviewStartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Restapi_CreateInterview.cls
@RestResource(urlMapping='/CreateInterview/*')
global with sharing class Restapi_CreateInterview {

    @HttpPost
    global static Interview__c doPost(String positionId, String candidateId, Datetime startDateTime, Integer duration) {
        Interview__c interviewToUpdate;
        try {
            interviewToUpdate = new Interview__c(
                Position__c = positionId,
                Candidate__c = candidateId,
                InterviewStartDateTime__c =  startDateTime,
                Duration__c = duration
            );
            
            Insert interviewToUpdate;

        } catch (Exception ex) {
            Log.error(ex.getMessage());
            throw ex;
        }

        return interviewToUpdate;
    }
}